// Generated by tools/gen_assets.py - do not edit.
#ifndef ASSETS_H
#define ASSETS_H

#include <stdint.h>

#define TITLE_FROG_X 120
#define TITLE_FROG_Y 100
#define FROG_TILE 4
#define NUM_COLORS 5
#define FROG_PALBANK 5
#define FONT_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:!->"
#define FONT_NCHARS 41
#define FRAME_TILE 164
#define NUM_LAYOUTS 6
#define NUM_THEMES 5
#define BG_FIRST_COLOR 32
#define BG_IMG_WORDS 9600

typedef struct {
    const int16_t *x, *y;   // path points, 1px apart
    int16_t len;
    int16_t hide;           // balls before this point are inside the serpent
    int16_t frog_x, frog_y;
} Layout;

extern const Layout layouts[NUM_LAYOUTS];
extern const int16_t sin_tab[256];
extern const uint16_t font_pal[16];
extern const uint16_t obj_pal[96];
extern const uint16_t title_pal[256];
extern const uint32_t title_tiles[BG_IMG_WORDS];
extern const uint16_t *const level_pal[NUM_LAYOUTS][NUM_THEMES];
extern const uint32_t *const level_tiles[NUM_LAYOUTS][NUM_THEMES];
extern const uint32_t obj_tiles[160];
extern const uint32_t font_tiles[1376];

#endif
