// Generated by tools/gen_assets.py - do not edit.
#ifndef ASSETS_H
#define ASSETS_H

#include <stdint.h>

#define PATH_LEN 727
#define FROG_X 120
#define FROG_Y 84
#define FROG_TILE 4
#define NUM_COLORS 5
#define FROG_PALBANK 5
#define FONT_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:!-"

extern const int16_t path_x[PATH_LEN];
extern const int16_t path_y[PATH_LEN];
extern const int16_t sin_tab[256];
extern const uint16_t bg_pal[32];
extern const uint16_t obj_pal[96];
extern const uint32_t bg_tiles[4800];
extern const uint32_t obj_tiles[160];
extern const uint32_t font_tiles[320];

#endif
